SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - nomidi\SeoHeroTool\SeoHeroToolController
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - nomidi\SeoHeroTool\SeoHeroToolDataObject
    - nomidi\SeoHeroTool\SeoHeroToolSchemaDataObject
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'nomidi/silverstripe-seo-hero-tool:client/dist/css/style.css'
