SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - nomidi\SeoHeroTool\SeoHeroToolController
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - nomidi\SeoHeroTool\SeoHeroToolDataObject
    - nomidi\SeoHeroTool\SeoHeroToolSchemaDataObject
